services:
  postgres:
    image: my-postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mydb
    ports:
      - "5555:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: